# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('huddleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 26, 23, 25, 57, 638620, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
