# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddleapp', '0003_followup_followupcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instructor_answer',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='student_answer',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
